export default {
  LOADING: 'LOADING',
  LOADED: 'LOADED',

  SET_USER: 'SET_USER',
  SET_USERS: 'SET_USERS',
  SET_TOKEN: 'SET_TOKEN',
  SET_ERROR: 'SET_ERROR',

  AUTHENTICATED: 'AUTHENTICATED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',

  CREATING: 'CREATING',
  CREATED: 'CREATED',

  VIEWING: 'VIEWING',
  VIEWED: 'VIEWED',

  REMOVING: 'REMOVING',
  REMOVED: 'REMOVED',

  UPDATING: 'UPDATING',
  UPDATED: 'UPDATED',
  SET_LOGIN: 'SET_LOGIN',
  SET_LOGOUT: 'SET_LOGOUT'
}
